name: Branding check

on:
  push:
    branches: [ main ]

jobs:
  check-branding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run logo check
        run: |
          npm ci --no-audit --prefer-offline || true
          node ./scripts/check_logo_exists.js
